
pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install .
      - pip install -r tests/requirements.txt
      - make test

matrix:
  PYTHON_VERSION:
    - 2.7-wheezy
    - 3.6-jessie
    - 3.5-jessie
